%%
%% Autogenerated by Thrift Compiler (0.9.1)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(alarmView_thrift).
-behaviour(thrift_service).


-include("alarmView_thrift.hrl").

-export([struct_info/1, function_info/2]).

struct_info('i am a dummy struct') -> undefined.
%%% interface
% ping(This)
function_info('ping', params_type) ->
  {struct, []}
;
function_info('ping', reply_type) ->
  {struct, []};
function_info('ping', exceptions) ->
  {struct, []}
;
% getCurrents(This)
function_info('getCurrents', params_type) ->
  {struct, []}
;
function_info('getCurrents', reply_type) ->
  {list, {struct, {'alarm_types', 'current'}}};
function_info('getCurrents', exceptions) ->
  {struct, [{1, {struct, {'alarm_types', 'alarmException'}}}]}
;
% getDetail(This, Id)
function_info('getDetail', params_type) ->
  {struct, [{1, i64}]}
;
function_info('getDetail', reply_type) ->
  {struct, {'alarm_types', 'detail'}};
function_info('getDetail', exceptions) ->
  {struct, [{1, {struct, {'alarm_types', 'alarmException'}}}]}
;
% getCurrent(This, Id)
function_info('getCurrent', params_type) ->
  {struct, [{1, i64}]}
;
function_info('getCurrent', reply_type) ->
  {struct, {'alarm_types', 'current'}};
function_info('getCurrent', exceptions) ->
  {struct, [{1, {struct, {'alarm_types', 'alarmException'}}}]}
;
function_info(_Func, _Info) -> no_function.

