%%
%% Autogenerated by Thrift Compiler (0.9.1)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(alarm_types).

-include("alarm_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info('alarmException') ->
  {struct, [{1, string}]}
;

struct_info('alarmKey') ->
  {struct, [{1, string},
          {2, string},
          {3, string}]}
;

struct_info('alarm') ->
  {struct, [{1, {struct, {'alarm_types', 'alarmKey'}}},
          {2, i32},
          {3, string},
          {4, i64},
          {5, string}]}
;

struct_info('detail') ->
  {struct, [{1, i64},
          {2, i64},
          {3, string}]}
;

struct_info('current') ->
  {struct, [{1, i64},
          {2, {struct, {'alarm_types', 'alarmKey'}}},
          {3, string},
          {4, i32},
          {5, i32},
          {6, i64},
          {7, i64},
          {8, i64},
          {9, i64}]}
;

struct_info('i am a dummy struct') -> undefined.

struct_info_ext('alarmException') ->
  {struct, [{1, undefined, string, 'message', undefined}]}
;

struct_info_ext('alarmKey') ->
  {struct, [{1, undefined, string, 'label', undefined},
          {2, undefined, string, 'source', undefined},
          {3, undefined, string, 'host', undefined}]}
;

struct_info_ext('alarm') ->
  {struct, [{1, undefined, {struct, {'alarm_types', 'alarmKey'}}, 'key', #alarmKey{}},
          {2, undefined, i32, 'level', undefined},
          {3, undefined, string, 'summary', undefined},
          {4, undefined, i64, 'timestamp', undefined},
          {5, optional, string, 'detail', undefined}]}
;

struct_info_ext('detail') ->
  {struct, [{1, undefined, i64, 'id', undefined},
          {2, undefined, i64, 'alertTime', undefined},
          {3, undefined, string, 'detail', undefined}]}
;

struct_info_ext('current') ->
  {struct, [{1, undefined, i64, 'id', undefined},
          {2, undefined, {struct, {'alarm_types', 'alarmKey'}}, 'key', #alarmKey{}},
          {3, undefined, string, 'summary', undefined},
          {4, undefined, i32, 'primelLevel', undefined},
          {5, undefined, i32, 'currentLevel', undefined},
          {6, undefined, i64, 'count', undefined},
          {7, undefined, i64, 'firstTime', undefined},
          {8, undefined, i64, 'lastTime', undefined},
          {9, optional, i64, 'resumeTime', undefined}]}
;

struct_info_ext('i am a dummy struct') -> undefined.

