%%
%% Autogenerated by Thrift Compiler (0.9.1)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(alertor_thrift).
-behaviour(thrift_service).


-include("alertor_thrift.hrl").

-export([struct_info/1, function_info/2]).

struct_info('i am a dummy struct') -> undefined.
%%% interface
% ping(This)
function_info('ping', params_type) ->
  {struct, []}
;
function_info('ping', reply_type) ->
  {struct, []};
function_info('ping', exceptions) ->
  {struct, []}
;
% alert(This, Alarm)
function_info('alert', params_type) ->
  {struct, [{1, {struct, {'alarm_types', 'alarm'}}}]}
;
function_info('alert', reply_type) ->
  {struct, []};
function_info('alert', exceptions) ->
  {struct, [{1, {struct, {'alarm_types', 'alarmException'}}}]}
;
% resume(This, Key)
function_info('resume', params_type) ->
  {struct, [{1, {struct, {'alarm_types', 'alarmKey'}}}]}
;
function_info('resume', reply_type) ->
  {struct, []};
function_info('resume', exceptions) ->
  {struct, [{1, {struct, {'alarm_types', 'alarmException'}}}]}
;
function_info(_Func, _Info) -> no_function.

