/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace baidu91.appsvc.demo
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SimpleSoft : TBase
  {
    private long _softid;
    private string _name;
    private string _vender;
    private byte[] _icon;

    public long softid
    {
      get
      {
        return _softid;
      }
      set
      {
        __isset.softid = true;
        this._softid = value;
      }
    }

    public string name
    {
      get
      {
        return _name;
      }
      set
      {
        __isset.name = true;
        this._name = value;
      }
    }

    public string vender
    {
      get
      {
        return _vender;
      }
      set
      {
        __isset.vender = true;
        this._vender = value;
      }
    }

    public byte[] icon
    {
      get
      {
        return _icon;
      }
      set
      {
        __isset.icon = true;
        this._icon = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool softid;
      public bool name;
      public bool vender;
      public bool icon;
    }

    public SimpleSoft() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64) {
              softid = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              name = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.String) {
              vender = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.String) {
              icon = iprot.ReadBinary();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SimpleSoft");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.softid) {
        field.Name = "softid";
        field.Type = TType.I64;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(softid);
        oprot.WriteFieldEnd();
      }
      if (name != null && __isset.name) {
        field.Name = "name";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(name);
        oprot.WriteFieldEnd();
      }
      if (vender != null && __isset.vender) {
        field.Name = "vender";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(vender);
        oprot.WriteFieldEnd();
      }
      if (icon != null && __isset.icon) {
        field.Name = "icon";
        field.Type = TType.String;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(icon);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SimpleSoft(");
      sb.Append("softid: ");
      sb.Append(softid);
      sb.Append(",name: ");
      sb.Append(name);
      sb.Append(",vender: ");
      sb.Append(vender);
      sb.Append(",icon: ");
      sb.Append(icon);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
