{"src/*",     [debug_info,{i, "include"},{i, "../dsf_base/include"}, {outdir, "ebin"}]}.
{"src/*/*",   [debug_info,{i, "include"},{i, "../dsf_base/include"}, {outdir, "ebin"}]}.
{"./src/*",   [debug_info,{i, "include"},{i, "../dsf_base/include"}, {outdir, "../rel/unicorn_release/lib/dsf_base-1.0/ebin"}]}.
{"./src/*/*", [debug_info,{i, "include"},{i, "../dsf_base/include"}, {outdir, "../rel/unicorn_release/lib/dsf_base-1.0/ebin"}]}.
{"../dsf_base/src/*", [debug_info,{i, "include"}, {i, "../dsf_base/include"}, {outdir, "../rel1/unicorn_release/lib/dsf_base-1.0/ebin"}]}.
{"../dsf_base/src/*/*", [debug_info,{i, "include"}, {i, "../dsf_base/include"}, {outdir, "../rel1/unicorn_release/lib/dsf_base-1.0/ebin"}]}.


